

"""Post Processor for text generated by parsers
"""
class PostProcessor:

    def __init__(self):
        pass

    def post_process_txt(self, extracted_txt_str: list(str)):
        raise NotImplementedError("This function is not implemented yet.")